
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hsmtojqwtfngzqinlrfv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImhzbXRvanF3dGZuZ3pxaW5scmZ2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDcyMjIwODgsImV4cCI6MjA2Mjc5ODA4OH0.JHvaYpJH7BG2wp3zVsL6w_D7u7ZHt2HBgpIkTVBRGd4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    persistSession: true,
    autoRefreshToken: true,
    storage: localStorage
  }
});
